travis:
  secure:
    BINSTAR_TOKEN: klbMvU3o2zWkXXgoykd09kfRft+FbiESPj5O+N24rDZAS3XMOIjC7Cag9Q7dKDJhBg4glEvlFd8xhiZHiw1gnGShW9lz41GBJlbRBdFr3pT6X+Ce36sduuZD5gL6F6vyMASWv5X8qOdXWsZ0hlEFuOaNQJGeKXMC1Rnz75TJN9sqZoz+7ORMjGuxXo8ysGX3Mm0lLeWIVzoZHjcYNWqaKpKlsj4yha7J6AivusUMYwkEK3F/Xqiq5cdWKD+aqdSQ+Wf0c8Mzhug0Yxy8F+5oMdLgsTN5Ht9qUO0qXIENexCjZ4EtV+nFsVT1KAH/pVnfBqlN1SLm6pNDgbq8US7HeXV/DslgiLv86YY/7zULFpBnkpAcQKKjOncrs0rE3HVWoAvMaJK31hf1EsTXpQeUKAkeFgkCBqDFx+1rbkVy1f0DtzPajP5UH9Rec95RjnYRFNsYyj6xz2rB0Yr+KUMYxV+wsaVK5poUQpugyTmhI/3PHtHcEf68dQTzACqyActreKUSKTFvCQbjRWvpLGLjuGe+YaEd8zaGj/kHTJ1TC1ug6HrZclX9GToi4YzVOxVmKRp6e7sniNlYRZvlxGMPlt8KJaBMtSpwMzhUAlORpWAWKm2ljRijgYWtB4KBw2Ucb2es7MruqKbKWmMRF+PXedVT2jldxHewczHkYvM8Smg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1

provider:
  osx: azure

azure:
  upload_packages: true
